[package]
name = "bevy_replicon"
version = "0.27.0-rc.1"
authors = [
  "Hennadii Chernyshchyk <genaloner@gmail.com>",
  "koe <ukoe@protonmail.com>",
]
edition = "2021"
description = "High level networking for the Bevy game engine"
readme = "README.md"
repository = "https://github.com/projectharmonia/bevy_replicon"
keywords = [
  "bevy",
  "multiplayer",
  "netcode",
  "replication",
  "server-authoritative",
]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"
include = ["/benches", "/src", "/tests", "/LICENSE*"]

[dependencies]
bevy = { version = "0.14.0-rc.2", default-features = false, features = [
  "bevy_scene",
] }
bytes = "1.5"
bincode = "1.3"
serde = "1.0"
varint-rs = "2.2"
ordered-multimap = "0.7"

[dev-dependencies]
bevy = { version = "0.14.0-rc.2", default-features = false, features = [
  "serialize",
  "bevy_asset",
  "bevy_sprite",
] }
criterion = { version = "0.5", default-features = false, features = [
  "cargo_bench_support",
] }

[lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[[bench]]
name = "replication"
harness = false

[workspace]
members = ["bevy_replicon_renet"]
