[package]
name = "bevy_replicon"
version = "0.11.0"
authors = ["Hennadii Chernyshchyk <genaloner@gmail.com>"]
edition = "2021"
rust-version = "1.65"
description = "High level networking for the Bevy game engine"
readme = "README.md"
repository = "https://github.com/lifescape-game/bevy_replicon"
keywords = [
  "bevy",
  "multiplayer",
  "netcode",
  "replication",
  "server-authoritative",
]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"
include = ["/benches", "/src", "/tests", "/LICENSE*"]

[dependencies]
bevy_renet = "0.0.9"
bevy = { version = "0.11", default-features = false, features = ["bevy_scene"] }
bincode = "1.3"
serde = "1.0"
strum = { version = "0.25", features = ["derive"] }
derive_more = { version = "0.99", default-features = false, features = [
  "constructor",
] }

[dev-dependencies]
serde_test = "1.0"
criterion = { version = "0.5", default-features = false, features = [
  "cargo_bench_support",
] }
spin_sleep = "1.1"
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
bevy = { version = "0.11", default-features = false, features = [
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "x11",
  "default_font",
] }

[[bench]]
name = "replication"
harness = false
